In [4]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd
import plotly.graph_objects as go
from plotly.offline import iplot

In [6]:
df = pd.read_csv("./datasets/Height_weight.csv")

In [7]:
df

Height  Weight
0     1.47   52.21
1     1.50   53.12
2     1.52   54.48
3     1.55   55.84
4     1.57   57.20
5     1.60   58.57
6     1.63   59.93
7     1.65   61.29
8     1.68   63.11
9     1.70   64.47
10    1.73   66.28
11    1.75   68.10
12    1.78   69.92
13    1.80   72.19
14    1.83   74.46
15    1.23     NaN

In [8]:
df[df.Weight.isnull()]

Height  Weight
15    1.23     NaN

In [9]:
df.Weight.fillna(df.Weight.mean() ,  inplace= True)
df

C:\Users\OM MAKWANA\AppData\Local\Temp\ipykernel_2424\669306768.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.





Height  Weight
0     1.47  52.210
1     1.50  53.120
2     1.52  54.480
3     1.55  55.840
4     1.57  57.200
5     1.60  58.570
6     1.63  59.930
7     1.65  61.290
8     1.68  63.110
9     1.70  64.470
10    1.73  66.280
11    1.75  68.100
12    1.78  69.920
13    1.80  72.190
14    1.83  74.460
15    1.23  62.078

In [10]:
df.shape

(16, 2)

In [11]:
ind = df["Height"].values
dep = df["Weight"].values

In [12]:
ind = df.iloc[:, 0:1].values
dep = df.Weight.values

In [13]:
# ind = df["Height"].values
# ind = df["Weight"].values

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
model = LinearRegression()


In [16]:
model = model.fit(ind , dep)


In [17]:
model.predict([[1.34], [2.14]])

array([52.94616835, 78.63571672])

In [18]:
# y  = mx  + c

In [19]:
# c = model.intercept_
# m = model.coef_

In [20]:
# m * 1.34 + c

In [21]:
ind.reshape(1 ,-1)[0]

array([1.47, 1.5 , 1.52, 1.55, 1.57, 1.6 , 1.63, 1.65, 1.68, 1.7 , 1.73,
       1.75, 1.78, 1.8 , 1.83, 1.23])

In [22]:
pred = model.predict(ind)
pred

array([57.12071996, 58.08407803, 58.72631674, 59.6896748 , 60.33191351,
       61.29527157, 62.25862964, 62.90086835, 63.86422641, 64.50646512,
       65.46982318, 66.11206189, 67.07541996, 67.71765866, 68.68101673,
       49.41385545])

In [23]:
actObj = go.Scatter(x = ind.reshape(1, -1)[0], y = dep, mode="markers")
predObj = go.Scatter(x = ind.reshape(1 , -1)[0], y =dep)

In [24]:
iplot([actObj, predObj])

In [25]:
# # mathod 1
# updated_arr = []
# for i in ind:
#     updated_arr.append([float(i)])
# ind

In [26]:
# method 2
# ind_2 = df.iloc[:, 0:1].values
# ind_2

In [27]:
# method 3
# ind = ind.reshape(-1, 1)
# ind

In [28]:
# df.fillna(df.Weight.mean(), inplace =  True)
# df

In [29]:
df = pd.read_csv("./datasets/loanf.csv")

In [30]:
df

Interest.Rate  FICO.Score  Loan.Length  Monthly.Income  Loan.Amount
6             15.31         670           36         4891.67         6000
11            19.72         670           36         3575.00         2000
12            14.27         665           36         4250.00        10625
13            21.67         670           60        14166.67        28000
21            21.98         665           36         6666.67        22000
...             ...         ...          ...             ...          ...
2472           7.90         770           36         5166.67        19000
2481           6.03         760           36         5000.00        10000
2482           6.62         810           36         9250.00        27000
2486          10.75         765           36         7083.33        25000
2497          14.09         740           60         8903.25        16000

[2500 rows x 5 columns]

In [31]:
df.shape

(2500, 5)

In [32]:
df.columns

Index(['Interest.Rate', 'FICO.Score', 'Loan.Length', 'Monthly.Income',
       'Loan.Amount'],
      dtype='object')

In [33]:
ind  =  df[["FICO.Score", "Loan.Amount"]].values
dep = df["Interest.Rate"]


In [34]:
from sklearn.linear_model import LinearRegression

In [35]:
model = LinearRegression()
model = model.fit(ind, dep)

In [36]:
model.predict([[200, 20000]])

array([59.40926925])

In [37]:
%pip install ipywidgets

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [38]:
def InterestRate(FICO, Amount):
    pred = model.predict([[FICO, Amount]])[0]
    print("For", Amount, "Your loan interest rate will be", int(pred))

In [39]:
InterestRate(600, 1200)

For 1200 Your loan interest rate will be 20


In [40]:
from ipywidgets import interact

In [42]:
interact(InterestRate, FICO = [100, 1200], Amount = (1000, 100000))

interactive(children=(Dropdown(description='FICO', options=(100, 1200), value=100), IntSlider(value=50500, des…

<function __main__.InterestRate(FICO, Amount)>